[package]
name = "anstic"
version = "0.1.0"
authors = ["Moojok <hey@moojok.online>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.6"
pest_derive = "2.6"

[lib]
path = "src/lib.rs"
